# Generated by Django 3.1.3 on 2020-11-21 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Instagram', '0002_image_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='comments',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='image',
            name='imageName',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='image',
            name='likes',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='image',
            name='profile',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Instagram.profile'),
        ),
    ]
